create table if not exists public.problems (
  id bigint generated by default as identity primary key,
  latex_code text not null,
  solution_latex text,
  answer_text text,
  question_type text not null default 'MC',
  difficulty text not null,
  topic text not null,
  sub_type text not null,
  grade text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.problems
add column if not exists solution_latex text;

alter table public.problems
add column if not exists answer_text text;

alter table public.problems
add column if not exists question_type text not null default 'MC';

alter table public.problems
add column if not exists latex_code_original text;

alter table public.problems
add column if not exists solution_latex_original text;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_problems_updated_at on public.problems;
create trigger trg_problems_updated_at
before update on public.problems
for each row execute function public.set_updated_at();

alter table public.problems enable row level security;

create index if not exists idx_problems_grade_labels
on public.problems(grade, difficulty, topic, sub_type);

create index if not exists idx_problems_practice_labels
on public.problems(difficulty, topic, sub_type);

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text not null,
  role text not null check (role in ('student', 'teacher', 'admin')),
  grade text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_profiles
add column if not exists class_name text;

alter table public.user_profiles
drop constraint if exists user_profiles_role_check;

alter table public.user_profiles
add constraint user_profiles_role_check check (role in ('student', 'teacher', 'admin'));

create table if not exists public.class_teacher_assignments (
  id bigint generated by default as identity primary key,
  class_name text not null,
  teacher_id uuid not null references public.user_profiles(user_id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (class_name, teacher_id)
);

alter table public.class_teacher_assignments enable row level security;

alter table public.study_groups
add column if not exists owner_teacher_id uuid references public.user_profiles(user_id) on delete set null;

create table if not exists public.daily_assignments (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.user_profiles(user_id) on delete cascade,
  assignment_date date not null,
  question_id bigint not null references public.problems(id) on delete cascade,
  slot integer not null check (slot between 1 and 5),
  created_at timestamptz not null default now(),
  unique (student_id, assignment_date, question_id),
  unique (student_id, assignment_date, slot)
);

alter table public.daily_assignments
drop constraint if exists daily_assignments_slot_check;

alter table public.daily_assignments
add constraint daily_assignments_slot_check check (slot > 0);

create table if not exists public.student_submissions (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.user_profiles(user_id) on delete cascade,
  assignment_date date not null,
  question_id bigint not null references public.problems(id) on delete cascade,
  answer_text text not null,
  is_correct boolean,
  time_spent_seconds integer,
  submitted_at timestamptz not null default now(),
  unique (student_id, assignment_date, question_id)
);

alter table public.student_submissions
add column if not exists time_spent_seconds integer;

create index if not exists idx_student_submissions_student_date
on public.student_submissions(student_id, assignment_date);

create table if not exists public.student_practice_submissions (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.user_profiles(user_id) on delete cascade,
  question_id bigint not null references public.problems(id) on delete cascade,
  answer_text text not null,
  is_correct boolean,
  time_spent_seconds integer,
  submitted_at timestamptz not null default now()
);

create index if not exists idx_student_practice_submissions_student_created
on public.student_practice_submissions(student_id, submitted_at desc);

create index if not exists idx_student_practice_submissions_question
on public.student_practice_submissions(question_id);

create table if not exists public.study_groups (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.student_group_memberships (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.user_profiles(user_id) on delete cascade,
  group_id bigint not null references public.study_groups(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (student_id, group_id)
);

create table if not exists public.study_group_scopes (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.study_groups(id) on delete cascade,
  difficulty text not null,
  min_difficulty text,
  max_difficulty text,
  topic text not null,
  sub_type text,
  created_at timestamptz not null default now()
);

alter table public.study_group_scopes
add column if not exists min_difficulty text;

alter table public.study_group_scopes
add column if not exists max_difficulty text;

update public.study_group_scopes
set max_difficulty = coalesce(max_difficulty, difficulty),
    min_difficulty = coalesce(min_difficulty, 'lv2')
where max_difficulty is null or min_difficulty is null;

create unique index if not exists uq_study_group_scope_combo
on public.study_group_scopes(group_id, difficulty, topic, coalesce(sub_type, ''));

create table if not exists public.class_scopes (
  id bigint generated by default as identity primary key,
  class_name text not null,
  difficulty text not null,
  min_difficulty text,
  max_difficulty text,
  topic text not null,
  sub_type text,
  created_at timestamptz not null default now()
);

alter table public.class_scopes
add column if not exists min_difficulty text;

alter table public.class_scopes
add column if not exists max_difficulty text;

update public.class_scopes
set max_difficulty = coalesce(max_difficulty, difficulty),
    min_difficulty = coalesce(min_difficulty, 'lv2')
where max_difficulty is null or min_difficulty is null;

create unique index if not exists uq_class_scope_combo
on public.class_scopes(class_name, difficulty, topic, coalesce(sub_type, ''));

drop trigger if exists trg_user_profiles_updated_at on public.user_profiles;
create trigger trg_user_profiles_updated_at
before update on public.user_profiles
for each row execute function public.set_updated_at();

alter table public.user_profiles enable row level security;
alter table public.daily_assignments enable row level security;
alter table public.student_submissions enable row level security;
alter table public.student_practice_submissions enable row level security;
alter table public.study_groups enable row level security;
alter table public.student_group_memberships enable row level security;
alter table public.study_group_scopes enable row level security;
alter table public.class_scopes enable row level security;

create table if not exists public.student_learning_progress (
  student_id uuid not null references public.user_profiles(user_id) on delete cascade,
  difficulty text not null,
  topic text not null,
  sub_type text not null,
  streak_correct integer not null default 0,
  mastery_achieved boolean not null default false,
  review_stage integer not null default 0 check (review_stage between 0 and 6),
  next_review_date date,
  consolidation_due_date date,
  correction_due_date date,
  correction_wrong_streak integer not null default 0,
  ever_wrong boolean not null default false,
  is_paused boolean not null default false,
  pending_careless_retry boolean not null default false,
  careless_retry_date date,
  status text not null default 'UNKNOWN' check (status in ('UNKNOWN', 'KNOWN', 'MASTERED', 'BACKFILL', 'FROZEN')),
  consecutive_correct_count integer not null default 0,
  last_correct_date date,
  wrong_count integer not null default 0,
  backfill_correct_count integer not null default 0,
  careless_streak integer not null default 0,
  pending_retest_question_id bigint references public.problems(id) on delete set null,
  done_variants jsonb not null default '[]'::jsonb,
  initial_assessment_done boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (student_id, difficulty, topic, sub_type)
);

alter table public.student_learning_progress
add column if not exists status text not null default 'UNKNOWN'
check (status in ('UNKNOWN', 'KNOWN', 'MASTERED', 'BACKFILL', 'FROZEN'));

alter table public.student_learning_progress
add column if not exists consecutive_correct_count integer not null default 0;

alter table public.student_learning_progress
add column if not exists last_correct_date date;

alter table public.student_learning_progress
add column if not exists wrong_count integer not null default 0;

alter table public.student_learning_progress
add column if not exists backfill_correct_count integer not null default 0;

alter table public.student_learning_progress
add column if not exists careless_streak integer not null default 0;

alter table public.student_learning_progress
add column if not exists pending_retest_question_id bigint references public.problems(id) on delete set null;

alter table public.student_learning_progress
add column if not exists done_variants jsonb not null default '[]'::jsonb;

alter table public.student_learning_progress
add column if not exists initial_assessment_done boolean not null default false;

update public.student_learning_progress
set status = case
  when is_paused = true then 'FROZEN'
  when mastery_achieved = true and review_stage >= 6 then 'MASTERED'
  when mastery_achieved = true or review_stage > 0 then 'KNOWN'
  else 'UNKNOWN'
end
where status is null or status = 'UNKNOWN';

create index if not exists idx_student_learning_progress_due_review
on public.student_learning_progress(student_id, next_review_date);

create index if not exists idx_student_learning_progress_status
on public.student_learning_progress(student_id, status);

create table if not exists public.student_initial_assessments (
  student_id uuid primary key references public.user_profiles(user_id) on delete cascade,
  completed_at timestamptz not null default now(),
  lv2_correct integer not null default 0,
  lv3_correct integer not null default 0,
  lv4_correct integer not null default 0,
  lv5_correct integer not null default 0,
  start_difficulty text not null,
  created_at timestamptz not null default now()
);

alter table public.student_initial_assessments enable row level security;

create table if not exists public.student_initial_assessment_answers (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.user_profiles(user_id) on delete cascade,
  question_id bigint not null references public.problems(id) on delete cascade,
  answer_text text not null,
  is_correct boolean,
  submitted_at timestamptz not null default now(),
  unique (student_id, question_id)
);

create index if not exists idx_student_initial_assessment_answers_student
on public.student_initial_assessment_answers(student_id, submitted_at desc);

alter table public.student_initial_assessment_answers enable row level security;

create index if not exists idx_student_learning_progress_due_correction
on public.student_learning_progress(student_id, correction_due_date);

drop trigger if exists trg_student_learning_progress_updated_at on public.student_learning_progress;
create trigger trg_student_learning_progress_updated_at
before update on public.student_learning_progress
for each row execute function public.set_updated_at();

create table if not exists public.learning_alerts (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.user_profiles(user_id) on delete cascade,
  difficulty text not null,
  topic text not null,
  sub_type text not null,
  message text not null,
  is_resolved boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_learning_alerts_student_open
on public.learning_alerts(student_id, is_resolved, created_at desc);

alter table public.student_learning_progress enable row level security;
alter table public.learning_alerts enable row level security;

create table if not exists public.avatar_characters (
  id bigint generated by default as identity primary key,
  avatar_key text not null unique,
  name text not null,
  tier text not null check (tier in ('basic', 'premium')),
  token_cost integer not null default 0 check (token_cost >= 0),
  emoji text,
  image_url text,
  model_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.avatar_characters
add column if not exists drop_rate numeric not null default 1;

create table if not exists public.student_token_wallets (
  student_id uuid primary key references public.user_profiles(user_id) on delete cascade,
  balance integer not null default 0 check (balance >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_student_token_wallets_updated_at on public.student_token_wallets;
create trigger trg_student_token_wallets_updated_at
before update on public.student_token_wallets
for each row execute function public.set_updated_at();

create table if not exists public.student_token_ledger (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.user_profiles(user_id) on delete cascade,
  delta_tokens integer not null,
  reason text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_student_token_ledger_student_created
on public.student_token_ledger(student_id, created_at desc);

create table if not exists public.student_avatar_inventory (
  student_id uuid not null references public.user_profiles(user_id) on delete cascade,
  avatar_id bigint not null references public.avatar_characters(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  source text not null default 'purchase',
  primary key (student_id, avatar_id)
);

create table if not exists public.student_avatar_state (
  student_id uuid primary key references public.user_profiles(user_id) on delete cascade,
  selected_avatar_id bigint references public.avatar_characters(id) on delete set null,
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_student_avatar_state_updated_at on public.student_avatar_state;
create trigger trg_student_avatar_state_updated_at
before update on public.student_avatar_state
for each row execute function public.set_updated_at();

alter table public.avatar_characters enable row level security;
alter table public.student_token_wallets enable row level security;
alter table public.student_token_ledger enable row level security;
alter table public.student_avatar_inventory enable row level security;
alter table public.student_avatar_state enable row level security;

insert into public.avatar_characters (avatar_key, name, tier, token_cost, emoji, image_url, model_url, is_active)
values
  ('fox_scout', 'Fox Scout', 'basic', 0, '🦊', null, null, true),
  ('owl_wiz', 'Owl Wiz', 'basic', 0, '🦉', null, null, true),
  ('cat_ninja', 'Cat Ninja', 'basic', 0, '🐱', null, null, true),
  ('dragon_neo', 'Neo Dragon', 'premium', 120, '🐉', null, null, true),
  ('robot_ace', 'Robot Ace', 'premium', 180, '🤖', null, null, true),
  ('space_bunny', 'Space Bunny', 'premium', 220, '🐰', null, null, true),
  ('middle_1', 'Middle 1', 'premium', 100, '🎓', '/assets/avatars/middle%201.png', null, true),
  ('middle_2', 'Middle 2', 'premium', 100, '🎓', '/assets/avatars/middle%202.png', null, true),
  ('middle_3', 'Middle 3', 'premium', 100, '🎓', '/assets/avatars/middle%203.png', null, true),
  ('middle_4', 'Middle 4', 'premium', 100, '🎓', '/assets/avatars/middle%204.png', null, true),
  ('middle_5', 'Middle 5', 'premium', 100, '🎓', '/assets/avatars/middle%205.png', null, true),
  ('middle_6', 'Middle 6', 'premium', 100, '🎓', '/assets/avatars/middle%206.png', null, true),
  ('middle_7', 'Middle 7', 'premium', 100, '🎓', '/assets/avatars/middle%207.png', null, true),
  ('middle_8', 'Middle 8', 'premium', 100, '🎓', '/assets/avatars/middle%208.png', null, true)
on conflict (avatar_key) do update set
  name = excluded.name,
  tier = excluded.tier,
  token_cost = excluded.token_cost,
  emoji = excluded.emoji,
  image_url = excluded.image_url,
  model_url = excluded.model_url,
  is_active = excluded.is_active;

update public.avatar_characters
set drop_rate = case avatar_key
  when 'fox_scout' then 32
  when 'owl_wiz' then 24
  when 'cat_ninja' then 18
  when 'dragon_neo' then 11
  when 'robot_ace' then 9
  when 'space_bunny' then 6
  when 'middle_1' then 10
  when 'middle_2' then 10
  when 'middle_3' then 10
  when 'middle_4' then 10
  when 'middle_5' then 10
  when 'middle_6' then 10
  when 'middle_7' then 10
  when 'middle_8' then 10
  else 1
end;

create table if not exists public.frame_items (
  id bigint generated by default as identity primary key,
  frame_key text not null unique,
  name text not null,
  tier text not null check (tier in ('basic', 'rare', 'epic', 'legendary')),
  style_key text not null,
  image_url text,
  drop_rate numeric not null default 1 check (drop_rate > 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.student_frame_inventory (
  student_id uuid not null references public.user_profiles(user_id) on delete cascade,
  frame_id bigint not null references public.frame_items(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  source text not null default 'gacha',
  primary key (student_id, frame_id)
);

create table if not exists public.student_frame_state (
  student_id uuid primary key references public.user_profiles(user_id) on delete cascade,
  selected_frame_id bigint references public.frame_items(id) on delete set null,
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_student_frame_state_updated_at on public.student_frame_state;
create trigger trg_student_frame_state_updated_at
before update on public.student_frame_state
for each row execute function public.set_updated_at();

alter table public.frame_items enable row level security;
alter table public.student_frame_inventory enable row level security;
alter table public.student_frame_state enable row level security;

insert into public.frame_items (frame_key, name, tier, style_key, image_url, drop_rate, is_active)
values
  ('frame_basic', 'Classic Frame', 'basic', 'basic', null, 36, true),
  ('frame_neon', 'Neon Frame', 'rare', 'neon', null, 24, true),
  ('frame_sakura', 'Sakura Frame', 'rare', 'sakura', null, 18, true),
  ('frame_aurora', 'Aurora Crown', 'epic', 'aurora', null, 11, true),
  ('frame_inferno', 'Inferno Ring', 'epic', 'inferno', null, 7, true),
  ('frame_holo', 'Holo Prism', 'legendary', 'holo', null, 3, true),
  ('frame_mythic', 'Mythic Orbit', 'legendary', 'mythic', null, 1, true),
  ('frame_crystal_scholar', 'Crystal Scholar Frame', 'legendary', 'image', '/assets/frames/crystal_scholar_frame.png', 2, true),
  ('frame_golden_champion', 'Golden Champion Frame', 'legendary', 'image', '/assets/frames/golden_champion_frame.png', 2, true),
  ('frame_cosmic_math', 'Cosmic Math Frame', 'legendary', 'image', '/assets/frames/cosmic_math_frame.png', 2, true),
  ('frame_fire_elementalist', 'Fire Elementalist Frame', 'legendary', 'image', '/assets/frames/fire_elementalist_frame.png', 2, true)
on conflict (frame_key) do update set
  name = excluded.name,
  tier = excluded.tier,
  style_key = excluded.style_key,
  image_url = excluded.image_url,
  drop_rate = excluded.drop_rate,
  is_active = excluded.is_active;
